Liquibase support, book soft delete and search (by author, price) were added
MaxSkory/online-book-store pull request #2
Opened 2023-10-11 13:15 UTC by MaxSkory

2023-10-11 20:23 UTC, Ivan95kos requested changes
Please, fix the conflicts
<img width="938" alt="Знімок екрана 2023-10-11 о 22 22 34" src="https://github.com/MaxSkory/online-book-store/assets/41166578/6988c736-65d6-46a4-9f22-ece1571ff884">

2023-10-12 11:28 UTC, kozhukhovsky approved these changes

2023-10-12 11:28 UTC, kozhukhovsky commented on src/main/java/mskory/bookstore/repository/book/specs/AuthorSpecificationProvider.java
> +
```suggestion
```

2023-10-12 11:28 UTC, kozhukhovsky commented on src/main/resources/db/changelog/changes/02-add-is-deleted-column-books-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2023-10-12 11:28 UTC, kozhukhovsky commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/03-add-scale-to-price-column-book-table.yaml
```suggestion
      file: db/changelog/changes/03-add-scale-to-price-column-book-table.yaml
      
```

2023-10-13 20:33 UTC, MaxSkory commented
sorry, forgot to merge previous PR 😕

2023-10-14 09:53 UTC, merged